language: node_js
node_js:
  - "0.12.7"
install:
  - "npm install"
  - "npm install bower -g"
  - "bower install"
  - "gem install scss_lint"
before_script:
  - npm install -g gulp
script:
  - "gulp dev-ci"
  - "gulp test"
env: CI=true

